

# -----------------------------------------------------
# Load single customization file (if exists)
# -----------------------------------------------------
[[ -f ~/.bashrc_custom ]] && source ~/.bashrc_custom
